### ISSUE TITLE
failed libgapii build on macOS / XCode 14.1

### ISSUE THREAD

**Issue by rosasco-wk** [google/agi#1239]
## CONFIG
M1 MBP running macOS 12.6.1 and XCode 14.1.

## STEPS TO REPRODUCE
CC=clang-12 bazel build --subcommands --config fuchsia_x64 //gapii/fuchsia:gapii 

## ERROR
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/breakpad/src/common/mac/macho_walker.cc:85:30: error: 'NXGetLocalArchInfo' is deprecated: first deprecated in macOS 13.0 [-Werror,-Wdeprecated-declarations]
    const NXArchInfo* arch = NXGetLocalArchInfo();
                             ^~~~~~~~~~~~~~~~~~
                             use macho_arch_name_for_mach_header()
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include/mach-o/arch.h:72:26: note: 'NXGetLocalArchInfo' has been explicitly marked deprecated here
extern const NXArchInfo *NXGetLocalArchInfo(void) __CCTOOLS_DEPRECATED_MSG("use macho_arch_name_for_mach_header()");
                         ^
external/breakpad/src/common/mac/macho_walker.cc:85:11: error: 'NXArchInfo' is deprecated: first deprecated in macOS 13.0 - No longer supported [-Werror,-Wdeprecated-declarations]
    const NXArchInfo* arch = NXGetLocalArchInfo();
          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include/mach-o/arch.h:58:27: note: 'NXArchInfo' has been explicitly marked deprecated here
typedef struct NXArchInfo NXArchInfo __CCTOOLS_DEPRECATED;
                          ^
2 errors generated.
Error in child process '/usr/bin/xcrun'. 1
Target //gapii/fuchsia:gapii failed to build

**Comment by rosasco-wk** [comment]
Breakpad bug filed: https://bugs.chromium.org/p/google-breakpad/issues/detail?id=872

**Comment by yalcinmelihyasin** [comment]
Same with #1240

**Comment by olehkuznetsov** [comment]
Fixed with 3.3.2
